In [3]:
import numpy as np

In [4]:
ftn = np.arange(10)
print(ftn)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
zm = np.zeros((3, 3), dtype=int)
print(zm)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
rm = np.random.randint(1, 11, size=(5, 5))
print(rm)

[[ 2  2 10  5  9]
 [10  8  3 10  1]
 [ 8  3  5  6  6]
 [ 7  1  7  5  3]
 [ 8  9  8 10  6]]


In [7]:
rnm = np.random.random((4, 4))
print(rnm)

[[0.67299437 0.78905169 0.74711083 0.67817975]
 [0.7537965  0.4041438  0.93909114 0.60247323]
 [0.0414344  0.25776928 0.30736026 0.81946527]
 [0.50310801 0.34998888 0.07755064 0.47430761]]


In [8]:
fv = np.random.randint(1, 11, 5)
sv = np.random.randint(1, 11, 5)
print(fv, sv)
print(fv + sv)
print(fv - sv)
print(fv * sv)

[4 3 9 3 7] [9 1 4 6 1]
[13  4 13  9  8]
[-5  2  5 -3  6]
[36  3 36 18  7]


In [9]:
rv1 = np.random.randint(1, 11, 7)
rv2 = np.random.randint(1, 11, 7)
print(rv1, rv2)
print(np.dot(rv1, rv2))

[ 3  3  9  4 10  4  7] [ 1  5 10  8 10  9  4]
304


In [10]:
rm1 = np.random.randint(1, 11, size=(2, 2))
rm2 = np.random.randint(1, 11, size=(2, 3))
print(rm1, rm2)
print(np.dot(rm1, rm2))

[[7 1]
 [6 6]] [[7 5 9]
 [1 2 8]]
[[ 50  37  71]
 [ 48  42 102]]


In [13]:
rm = np.random.randint(1, 11, size=(3, 3))
print(rm)
rm_ins = np.linalg.inv(rm)
print(rm_ins)

[[5 2 5]
 [3 1 8]
 [1 8 1]]
[[ 0.33157895 -0.2        -0.05789474]
 [-0.02631579  0.          0.13157895]
 [-0.12105263  0.2         0.00526316]]


In [14]:
rm = np.random.randint(1, 11, size=(4, 4))
print(rm)
transrm = rm.T
print(transrm)

[[1 2 7 8]
 [1 4 8 1]
 [9 5 9 2]
 [1 6 5 7]]
[[1 1 9 1]
 [2 4 5 6]
 [7 8 9 5]
 [8 1 2 7]]


In [15]:
rm = np.random.randint(1, 11, size=(3, 4))
rv = np.random.randint(1, 11, 4)
print(rm, rv)
print(np.dot(rm, rv))

[[ 2 10  6  3]
 [ 4  8  8  2]
 [ 9  1  7  7]] [4 2 4 7]
[ 73  78 115]


In [16]:
rnm = np.random.random((2, 3))
rnv = np.random.random(3)
print(rnm, rnv)
print(np.dot(rnm, rnv))

[[0.66349128 0.44750116 0.09747057]
 [0.75236432 0.10867498 0.13914554]] [0.26809067 0.53488147 0.76188154]
[0.49149693 0.36584251]


In [17]:
rm1 = np.random.randint(1, 11, size=(2, 2))
rm2 = np.random.randint(1, 11, size=(2, 2))
print(rm1, rm2)
print(rm1*rm2)

[[4 2]
 [8 6]] [[1 5]
 [5 6]]
[[ 4 10]
 [40 36]]


In [18]:
rm1 = np.random.randint(1, 11, size=(2, 2))
rm2 = np.random.randint(1, 11, size=(2, 2))
print(rm1, rm2)
print(rm1/rm2)

[[9 7]
 [2 5]] [[8 9]
 [6 8]]
[[1.125      0.77777778]
 [0.33333333 0.625     ]]


In [19]:
rm = np.random.randint(1, 101, size=(5, 5))
print(rm)
print(rm.sum())

[[59 27 24 15 20]
 [26 29 33 29  6]
 [96  4  2 99 10]
 [41 83 23 94 77]
 [49 23 93 53 45]]
1060


In [20]:
rm1 = np.random.randint(1, 11, size=(4, 4))
rm2 = np.random.randint(1, 11, size=(4, 4))
print(rm1, rm2)
print(rm1-rm2)

[[ 8  4  6 10]
 [ 7  1  3  4]
 [ 6  1  8  7]
 [10 10  5  7]] [[1 3 2 1]
 [7 1 5 9]
 [6 6 6 9]
 [3 4 5 6]]
[[ 7  1  4  9]
 [ 0  0 -2 -5]
 [ 0 -5  2 -2]
 [ 7  6  0  1]]


In [21]:
rnm = np.random.random((3, 3))
print(rnm)
resv = np.array([rnm[0].sum(), rnm[1].sum(), rnm[2].sum()])
print(resv)

[[0.56838417 0.76432031 0.19685208]
 [0.66897723 0.96466918 0.33936992]
 [0.73668166 0.24607167 0.67546546]]
[1.52955656 1.97301632 1.6582188 ]


In [22]:
rm = np.random.randint(1, 101, size=(3, 4))
print(rm)
resm = np.square(rm)
print(resm)

[[12 75 17 10]
 [94  4 38 51]
 [18 18  4 29]]
[[ 144 5625  289  100]
 [8836   16 1444 2601]
 [ 324  324   16  841]]


In [23]:
rv = np.random.randint(1, 51, 4)
print(rv)
resv = np.sqrt(rv)
print(resv)

[42 43 42 18]
[6.4807407  6.55743852 6.4807407  4.24264069]
